feat: Support the vote in the post
linuxdeepin/bbs-mobile-web pull request #10
Opened 2024-03-14 11:38 UTC by student-ice

帖子中支持投票功能

2024-03-14 11:44 UTC, myml requested changes

2024-03-14 11:44 UTC, myml commented on src/pages/thread/thread.vue
> +    threadRefresh.value
这部分有些奇怪

2024-03-14 11:44 UTC, myml commented on src/pages/thread/thread.vue
> +            <nut-col v-if="threadInfo.is_poll" class="vote-card" span="22" offset="1">
可以将投票抽称单独的组件，像send-post那样

2024-03-14 11:48 UTC, student-ice commented on src/pages/thread/thread.vue
> +    threadRefresh.value
投票之后，可以通过这个刷新帖子数据

2024-03-15 02:57 UTC, myml approved these changes

2024-03-15 02:57 UTC, merged